#!/usr/bin/env bash

## Copyright (C) 2020-2021 Aditya Shakya <adi1090x@gmail.com>
## Everyone is permitted to copy and distribute copies of this file under GNU-GPL3

## Environtment
export PATH="${PATH}:$HOME/.config/bspwm/bin"

autorandr --load default

## Get colors from .Xresources -------------------------------#
xrdb ~/.Xresources
getcolors() {
    # FOREGROUND=$(xrdb -query | grep 'foreground:'| awk '{print $NF}')
    # BACKGROUND=$(xrdb -query | grep 'background:'| awk '{print $NF}')
    # BLACK=$(xrdb -query | grep 'color0:'| awk '{print $NF}')
    # RED=$(xrdb -query | grep 'color1:'| awk '{print $NF}')
    # GREEN=$(xrdb -query | grep 'color2:'| awk '{print $NF}')
    # YELLOW=$(xrdb -query | grep 'color3:'| awk '{print $NF}')
    # BLUE=$(xrdb -query | grep 'color4:'| awk '{print $NF}')
    # MAGENTA=$(xrdb -query | grep 'color5:'| awk '{print $NF}')
    # CYAN=$(xrdb -query | grep 'color6:'| awk '{print $NF}')
    # WHITE=$(xrdb -query | grep 'color7:'| awk '{print $NF}')
    FOREGROUND=#D8DEE9
    BACKGROUND=#2E3440
    BLACK=#3B4252
    RED=#BF616A
    GREEN=#A3BE8C
    YELLOW=#EBCB8B
    BLUE=#81A1C1
    MAGENTA=#B48EAD
    CYAN=#88C0D0
    WHITE=#E5E9F0
    ALTBLACK=#4C566A
    ALTRED=#BF616A
    ALTGREEN=#A3BE8C
    ALTYELLOW=#EBCB8B
    ALTBLUE=#81A1C1
    ALTMAGENTA=#B48EAD
    ALTCYAN=#8FBCBB
    ALTWHITE=#ECEFF4
}
getcolors

## Configurations --------------------------------------------#
workspaces() {
    monitors=$(xrandr -q | grep -w connected | cut -d ' ' -f1 | tac)
    monitors_connected=$(echo $monitors | wc -w)

    bspc wm --reorder-monitors $monitors

    start_from=1
    per_monitor=$((10 / monitors_connected))

    for monitor in $monitors; do
        bspc monitor ${monitor} -d $(seq $start_from $((start_from + per_monitor - 1)))
        start_from=$((start_from + per_monitor))
    done
}
workspaces

bspc config border_width 5
bspc config window_gap 5
bspc config split_ratio 0.50

bspc config focused_border_color "$BLUE"
bspc config normal_border_color "$BACKGROUND"
bspc config active_border_color "$MAGENTA"
bspc config presel_feedback_color "$GREEN"

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer false

## Window rules ----------------------------------------------#

# remove all rules first
bspc rule -r *:*

# 1 > terminal
# declare -a terms=(kitty Alacritty Xfce4-terminal)
# for i in ${terms[@]}; do
#     bspc rule -a $i desktop='^1' follow=on focus=on
# done

# 2 > web
# declare -a browsers=(Google-chrome firefox chromium)
# for i in ${browsers[@]}; do
#     bspc rule -a $i desktop='^2' follow=on focus=on
# done

# 3 > files
# declare -a files=(Pcmanfm Thunar qBittorrent)
# for i in ${files[@]}; do
#    bspc rule -a $i desktop='^3' follow=on focus=on;
# done

# 4 > code
# declare -a code=(Geany code-oss code)
# for i in ${code[@]}; do
#    bspc rule -a $i desktop='^4' follow=on focus=on;
# done

# 5 > all others
# declare -a office=(Gucharmap Atril Evince \
# libreoffice-writer libreoffice-calc libreoffice-impress \
# libreoffice-startcenter libreoffice Soffice *:libreofficedev *:soffice)
# for i in ${office[@]}; do
#    bspc rule -a $i desktop='^5' follow=on focus=on;
# done

declare -a comm=(Thunderbird TelegramDesktop Hexchat)
for i in ${comm[@]}; do
   bspc rule -a $i desktop='^5' follow=on focus=on;
done

declare -a media=(Audacity Music MPlayer Lxmusic Inkscape Gimp-2.10 obs Netease-cloud-music-gtk Steam)
for i in ${media[@]}; do
   bspc rule -a $i desktop='^5' state=floating follow=on focus=on;
done

bspc rule -a 'VirtualBox Manager' desktop='^5' follow=on focus=on
bspc rule -a GParted desktop='^5' follow=on focus=on
declare -a settings=(Lxappearance Lxtask Lxrandr Arandr \
System-config-printer.py Pavucontrol Exo-helper-1 \
Xfce4-power-manager-settings)
for i in ${settings[@]}; do
   bspc rule -a $i desktop='^5' state=floating follow=on focus=on;
done

# special rules
declare -a floating=(alacritty-float Pcmanfm Onboard Yad 'Firefox:Places' \
Viewnior feh Nm-connection-editor Nvidia-settings zoom)
for i in ${floating[@]}; do
   bspc rule -a $i state=floating follow=on focus=on;
done

bspc rule -a Conky state=floating manage=off
bspc rule -a stalonetray state=floating manage=off

## Autostart -------------------------------------------------#

# Kill if already running
killall -9 xsettingsd sxhkd dunst ksuperkey xfce4-power-manager

# Lauch notification daemon
dunst \
-geom "280x50-10+42" -frame_width "1" -font "FiraCode Nerd Font Mono 9" \
-lb "$BACKGROUND" -lf "$FOREGROUND" -lfr "$BLUE" \
-nb "$BACKGROUND" -nf "$FOREGROUND" -nfr "$BLUE" \
-cb "$BACKGROUND" -cf "$RED" -cfr "$RED" &

# Lauch xsettingsd daemon
xsettingsd &

# polkit agent
if [[ ! `pidof xfce-polkit` ]]; then
    /usr/lib/xfce-polkit/xfce-polkit &
fi

# start fcitx
if [[ ! `pidof fcitx5` ]]; then
    systemctl --user start fcitx.service
fi

# Lauch keybindings daemon
sxhkd &

# Enable Super Keys For Menu
ksuperkey -e 'Super_L=Alt_L|F1' &
ksuperkey -e 'Super_R=Alt_L|F1' &

# Enable power management
# xfce4-power-manager &

# Fix cursor
xsetroot -cursor_name left_ptr

# Restore wallpaper
bash $HOME/.fehbg

# Start mpd
# exec mpd &

# Start bspwm scripts
bspcolors
bspbar
bspcomp
bspfloat &
