---
# Configuration for zellij.

# In order to troubleshoot your configuration try using the following command:
# `zellij setup --check`
# It should show current config locations and features that are enabled.

keybinds:
  unbind: true
  normal:
    - action: [SwitchToMode: Tmux,]
      key: [Ctrl: 'a',]
  locked:
    - action: [SwitchToMode: Tmux,]
      key: [Ctrl: 'a',]
  resize:
    - action: [SwitchToMode: Locked,]
      key: [Char: 'q', Char: "\n", Char: 'i', Esc]
    - action: [SwitchToMode: Tmux,]
      key: [Ctrl: 'a',]

    - action: [Resize: Left,]
      key: [Char: 'h',]
    - action: [Resize: Down,]
      key: [Char: 'j',]
    - action: [Resize: Up,]
      key: [Char: 'k', ]
    - action: [Resize: Right,]
      key: [Char: 'l',]

    - action: [Resize: Increase,]
      key: [Char: '=']
    - action: [Resize: Increase,]
      key: [ Char: '+']
    - action: [Resize: Decrease,]
      key: [Char: '-']
  pane:
    - action: [SwitchToMode: Locked,]
      key: [Char: 'q', Char: "\n", Char: 'i', Esc]
    - action: [SwitchToMode: Tmux,]
      key: [Ctrl: 'a',]

    - action: [MoveFocus: Left,]
      key: [ Char: 'h', Left,]
    - action: [MoveFocus: Right,]
      key: [ Char: 'l', Right,]
    - action: [MoveFocus: Down,]
      key: [ Char: 'j', Down,]
    - action: [MoveFocus: Up,]
      key: [ Char: 'k', Up,]

    - action: [SwitchToMode: RenamePane, PaneNameInput: [0],]
      key: [Char: 'r']
  move:
    - action: [SwitchToMode: Locked,]
      key: [Char: 'q', Char: 'i', Char: "\n", Esc]
    - action: [SwitchToMode: Tmux,]
      key: [Ctrl: 'a']

    - action: [MovePane: Left,]
      key: [Char: 'h',]
    - action: [MovePane: Down,]
      key: [Char: 'j',]
    - action: [MovePane: Up,]
      key: [Char: 'k', ]
    - action: [MovePane: Right,]
      key: [Char: 'l',]
  tab:
    - action: [SwitchToMode: Locked,]
      key: [Char: 'q', Char: 'i', Char: "\n", Esc]
    - action: [SwitchToMode: Tmux,]
      key: [Ctrl: 'a',]

    - action: [SwitchToMode: RenameTab, TabNameInput: [0],]
      key: [Char: 'r']

    - action: [GoToPreviousTab,]
      key: [ Char: 'h', Left, Up, Char: 'k',]
    - action: [GoToNextTab,]
      key: [ Char: 'l', Right,Down, Char: 'j']

    - action: [NewTab: , SwitchToMode: Locked,]
      key: [ Char: 'n',]
    - action: [CloseTab, SwitchToMode: Locked,]
      key: [ Char: 'x',]
    - action: [ToggleActiveSyncTab, SwitchToMode: Locked,]
      key: [Char: 's']

    - action: [GoToTab: 1, SwitchToMode: Locked,]
      key: [ Char: '1',]
    - action: [GoToTab: 2, SwitchToMode: Locked,]
      key: [ Char: '2',]
    - action: [GoToTab: 3, SwitchToMode: Locked,]
      key: [ Char: '3',]
    - action: [GoToTab: 4, SwitchToMode: Locked,]
      key: [ Char: '4',]
    - action: [GoToTab: 5, SwitchToMode: Locked,]
      key: [ Char: '5',]
    - action: [GoToTab: 6, SwitchToMode: Locked,]
      key: [ Char: '6',]
    - action: [GoToTab: 7, SwitchToMode: Locked,]
      key: [ Char: '7',]
    - action: [GoToTab: 8, SwitchToMode: Locked,]
      key: [ Char: '8',]
    - action: [GoToTab: 9, SwitchToMode: Locked,]
      key: [ Char: '9',]

  entersearch:
    - action: [SwitchToMode: Search]
      key: [Char: "\n"]
    - action: [SearchInput: [27], SwitchToMode: Search]
      key: [Esc]

  search:
    - action: [SwitchToMode: Tmux,]
      key: [Ctrl: 'a',]

    - action: [ScrollToBottom, SwitchToMode: Locked]
      key: [Char: 'q', Char: 'i', Char: "\n", Esc]

    - action: [EditScrollback, SwitchToMode: Locked]
      key: [Char: 'e']
    - action: [SwitchToMode: EnterSearch, SearchInput: [0]]
      key: [Char: '/']

    - action: [Search: Down]
      key: [Char: 'n']
    - action: [Search: Up]
      key: [Char: 'p']
    - action: [SearchToggleOption: CaseSensitivity]
      key: [Char: 'c']

    - action: [ScrollDown,]
      key: [Char: 'j', Down,]
    - action: [ScrollUp,]
      key: [Char: 'k', Up,]

    - action: [PageScrollDown,]
      key: [Ctrl: 'f', PageDown]
    - action: [PageScrollUp,]
      key: [Ctrl: 'b', PageUp]

    - action: [HalfPageScrollDown,]
      key: [Ctrl: 'd',]
    - action: [HalfPageScrollUp,]
      key: [Ctrl: 'u',]

  renametab:
    - action: [SwitchToMode: Locked,]
      key: [Esc]
    - action: [TabNameInput: [27] , SwitchToMode: Locked,]
      key: [Char: "\n",]
  renamepane:
    - action: [SwitchToMode: Locked,]
      key: [Esc]
    - action: [PaneNameInput: [27] , SwitchToMode: Locked,]
      key: [Char: "\n",]
  session:
    - action: [SwitchToMode: Tmux,]
      key: [Ctrl: 'a',]
    - action: [SwitchToMode: Locked,]
      key: [Char: 'q', Char: "\n", Char: 'i', Esc]
  tmux:
    # switch mode
    - action: [SwitchToMode: Tab,]
      key: [Char: 't']
    - action: [SwitchToMode: Move,]
      key: [Char: 'm']
    - action: [SwitchToMode: Pane,]
      key: [Char: 'p']
    - action: [SwitchToMode: Resize,]
      key: [Char: 'r']
    - action: [SwitchToMode: Session,]
      key: [Char: 's']
    - action: [SwitchToMode: Search,]
      key: [Char: '[']
    - action: [SwitchToMode: Locked,]
      key: [Char: 'q', Char: "\n", Char: 'i', Esc]

        # quit and detach
    - action: [Quit,]
      key: [Ctrl: 'q',]
    - action: [Detach,]
      key: [Char: 'd',]

        # quick new tab
    - action: [NewTab: , SwitchToMode: Locked,]
      key: [Char: 'c',]

    - action: [GoToPreviousTab, SwitchToMode: Locked,]
      key: [Ctrl: 'h']
    - action: [GoToNextTab, SwitchToMode: Locked,]
      key: [Ctrl: 'l']

    - action: [CloseFocus, SwitchToMode: Locked,]
      key: [Char: 'x',]

        # fullscreen and floating
    - action: [ToggleFocusFullscreen, SwitchToMode: Locked,]
      key: [Char: 'z',]
    - action: [ToggleFloatingPanes, SwitchToMode: Locked,]
      key: [Char: 'f']

        # split panel
    - action: [NewPane: Down, SwitchToMode: Locked,]
      key: [Ctrl: "s",]
    - action: [NewPane: Right, SwitchToMode: Locked,]
      key: [Ctrl: 'v',]

        # move focus
    - action: [MoveFocus: Left, SwitchToMode: Locked]
      key: [Char: 'h']
    - action: [MoveFocus: Right, SwitchToMode: Locked]
      key: [Char: 'l']
    - action: [MoveFocus: Down, SwitchToMode: Locked]
      key: [Char: 'j']
    - action: [MoveFocus: Up, SwitchToMode: Locked]
      key: [Char: 'k']

        # resize
    - action: [Resize: Left, SwitchToMode: Locked]
      key: [Char: 'H']
    - action: [Resize: Down, SwitchToMode: Locked]
      key: [Char: 'J']
    - action: [Resize: Up, SwitchToMode: Locked]
      key: [Char: 'K']
    - action: [Resize: Right, SwitchToMode: Locked]
      key: [Char: 'L']
    - action: [Resize: Increase, SwitchToMode: Locked]
      key: [Char: '+']
    - action: [Resize: Decrease, SwitchToMode: Locked]
      key: [Char: '-']

    - action: [TogglePaneFrames, SwitchToMode: Locked,]
      key: [Char: 'w',]

plugins:
- path: tab-bar
  tag: tab-bar
- path: status-bar
  tag: status-bar
- path: strider
  tag: strider
- path: compact-bar
  tag: compact-bar

# Choose what to do when zellij receives SIGTERM, SIGINT, SIGQUIT or SIGHUP
# eg. when terminal window with an active zellij session is closed
# Options:
#   - detach (Default)
#   - quit
#on_force_close: quit

# Send a request for a simplified ui (without arrow fonts) to plugins
# Options:
#   - true
#   - false (Default)
#simplified_ui: true

# Choose the path to the default shell that zellij will use for opening new panes
# Default: $SHELL
# default_shell: fish

# Toggle between having pane frames around the panes
# Options:
#   - true (default)
#   - false
pane_frames: false

# Choose the theme that is specified in the themes section.
# For some examples, see: https://github.com/zellij-org/zellij/tree/main/example/themes
# Default: default
theme: kanagawa

# Choose the mode that zellij uses when starting up.
# Default: normal
default_mode: locked

# Toggle enabling the mouse mode.
# On certain configurations, or terminals this could
# potentially interfere with copying text.
# Options:
#   - true (default)
#   - false
mouse_mode: false

# Configure the scroll back buffer size
# This is the number of lines zellij stores for each pane in the scroll back
# buffer. Excess number of lines are discarded in a FIFO fashion.
# Valid values: positive integers
# Default value: 10000
scroll_buffer_size: 20000

# Provide a command to execute when copying text. The text will be piped to
# the stdin of the program to perform the copy. This can be used with
# terminal emulators which do not support the OSC 52 ANSI control sequence
# that will be used by default if this option is not set.
# Examples:
#copy_command: "xclip -selection clipboard" # x11
#copy_command: "wl-copy"                    # wayland
#copy_command: "pbcopy"                     # osx

# Choose the destination for copied text
# Allows using the primary selection buffer (on x11/wayland) instead of the system clipboard.
# Does not apply when using copy_command.
# Options:
#   - system (default)
#   - primary
#copy_clipboard: primary

# Enable or disable automatic copy (and clear) of selection when releasing mouse
#copy_on_select: true

# Path to the default editor to use to edit pane scrollbuffer
# scrollback_editor: /usr/bin/nano

# default_layout: compact
