themes:
  kanagawa:
    fg:      0xdcd7ba
    bg:      0x1f1f28
    black:   0x3d3d3d
    red:     0x6673bf
    green:   0x3ea290
    yellow:  0xb0ead9
    blue:    0x31658c
    magenta: 0x596196
    cyan:    0x8292b2
    white:   0xc8cacc
