#!/usr/bin/env python
import json
import os
import sys

import requests

HOST_TOKEN = "https://api.github.com/copilot_internal/v2/token"
HOST_API = "https://api.githubcopilot.com/chat/completions"

system_prompt = """
You are a Unix shell assistant. Your task is to provide Unix shell command based on specific user descriptions or tasks.
Respond with only the necessary Unix command(s) that accomplish the user's described goal without additional commentary or explanation.

# Steps
- Read the task or goal described by the user carefully.
- Identify the most efficient and clear Unix command that will achieve the described task.
- Provide only the command necessary to accomplish the task. Do not include explanations, descriptions, or additional information.

# Output Format
- Output should be in plain text, consisting exclusively of the command needed to achieve the task as described by the user.
- Do not use markdown or any extra characters, just the shell command itself.
- If multiple commands are needed, join them with AND signs (&&).
"""


def get_oauth_token() -> str:
    config_dir = os.environ.get(
        "XDG_CONFIG_HOME", os.path.join(os.environ["HOME"], ".config")
    )

    with open(os.path.join(config_dir, "github-copilot/apps.json")) as f:
        obj = json.load(f)
        for key, value in obj.items():
            if key.startswith("github.com:"):
                return value["oauth_token"]
        raise RuntimeError("Could not find token")


def get_token() -> str:
    oauth_token = get_oauth_token()
    return requests.get(
        HOST_TOKEN,
        headers={
            "Authorization": f"Bearer {oauth_token}",
            "Accept": "application/json",
        },
    ).json()["token"]


def main():
    payload = {
        "model": "gpt-4o",
        "messages": [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": sys.stdin.read()},
        ],
    }
    token = get_token()
    rsp = requests.post(
        HOST_API,
        headers={
            "Authorization": f"Bearer {token}",
            "Copilot-Integration-Id": "vscode-chat",
            "editor-version": "Neovim/0.10.0",
        },
        json=payload,
    ).json()
    print(rsp["choices"][0]["message"]["content"])


if __name__ == "__main__":
    main()
