#!/usr/bin/env python
import json
import os
import sys
from abc import ABC, abstractmethod
from argparse import ArgumentParser

import requests

os_name = "MacOS" if os.uname().sysname == "Darwin" else "Linux"

prompts_lib = {
    "howto": f"""
You are an expert Unix shell command generator. Your sole purpose is to provide the most efficient and accurate Unix shell command(s) to fulfill user requests.

# Constraints
- Respond EXCLUSIVELY with the required Unix command(s) as plain text. Do NOT include any markdown code blocks (```), explanations, commentary, or additional text.
- The generated commands must be compatible with the operating system: {os_name}.
- Prioritize commands available in standard Unix utilities. Avoid external packages unless explicitly requested by the user.
- If a task requires multiple commands, chain them using '&&' or pipes ('|') as appropriate.

# Input
- The user will provide a description of a task or goal they wish to accomplish in the Unix shell.

# Output
- A single line containing ONLY the Unix command(s) that directly address the user's request, in plain text format.
- If multiple commands are needed, separate them with '&&' or '|' as appropriate.

# Example
User: List all files in the current directory, sorted by size.
Assistant: ls -lS

User: Find all files containing the word "error" in the /var/log directory.
Assistant: grep -r "error" /var/log

User: Create a new directory named "backup" and copy all .txt files from the current directory into it.
Assistant: mkdir backup && cp *.txt backup
""",
    "commit": """
Create a commit message based on the Conventional Commit Convention using the provided 'git diff --staged' output. The message should succinctly summarize the changes and their impact, following these guidelines:

- Title: Start with a commit type (e.g., fix, feat, refactor), include an optional scope in parentheses, and add a concise description within 74 characters, not ending with a period.
- Body: Provide more context or rationale behind the changes with detailed descriptions or bullet points.
- Footer: Add metadata like BREAKING CHANGE, if appropriate.
- Emojis: NO emojis.
- Line Breaks: Insert line breaks thoughtfully, mainly after periods.
- Semantic Release: Ensure the message aligns with semantic release guidelines for classifying release types.

Commit Types:

- refactor: Improve internal structure without altering external behavior.
- fix: Address issues to ensure functionality.
- feat: Introduce new features or functionalities.
- Additional types: build, chore, style, test, docs, perf, ci, revert, wip as previously detailed.

Craft the commit message focusing solely on the provided details, avoiding extraneous information or assumptions. Do not wrap your response in any markdown or code block syntax!
""",
}


class Adapter(ABC):
    @property
    @abstractmethod
    def token(self) -> str:
        pass

    @property
    @abstractmethod
    def base_url(self) -> str:
        pass

    @property
    @abstractmethod
    def model(self) -> str:
        pass

    @property
    def headers(self) -> dict[str, str]:
        return {
            "Authorization": f"Bearer {self.token}",
            "Content-Type": "application/json",
        }

    def ask(self, input: str, system_prompt: str = "") -> str:
        payload = {
            "model": self.model,
            "messages": [
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": input},
            ],
        }
        try:
            response = requests.post(
                f"{self.base_url}/chat/completions",
                headers=self.headers,
                json=payload,
            )
            response.raise_for_status()
            rsp = response.json()
            return rsp["choices"][0]["message"]["content"]
        except requests.exceptions.RequestException as e:
            return f"An error occurred: {e}"


class Copilot(Adapter):
    _USER_AGENT = "vscode-chat/dev"
    _OAUTH_TOKEN_URL = "https://api.github.com/copilot_internal/v2/token"

    @property
    def _oauth_token(self) -> str:
        config_dir = os.environ.get(
            "XDG_CONFIG_HOME", os.path.join(os.environ["HOME"], ".config")
        )

        with open(os.path.join(config_dir, "github-copilot/apps.json")) as f:
            obj = json.load(f)
            for key, value in obj.items():
                if key.startswith("github.com:"):
                    return value["oauth_token"]
            raise RuntimeError("Could not find token")

    @property
    def token(self) -> str:
        rsp = requests.get(
            self._OAUTH_TOKEN_URL,
            headers={
                "Authorization": f"Bearer {self._oauth_token}",
                "Accept": "application/json",
                "User-Agent": self._USER_AGENT,
            },
        )
        rsp.raise_for_status()
        token = rsp.json()["token"]
        return token

    @property
    def base_url(self) -> str:
        return "https://api.githubcopilot.com"

    @property
    def model(self) -> str:
        return os.environ.get("COPILOT_MODEL", "gpt-4o")

    @property
    def headers(self) -> dict[str, str]:
        return {
            "Authorization": f"Bearer {self.token}",
            "Content-Type": "application/json",
            "Copilot-Integration-Id": "vscode-chat",
            "editor-version": "Neovim/0.10.0",
            "User-Agent": self._USER_AGENT,
        }


class Deepseek(Adapter):
    @property
    def token(self) -> str:
        return os.environ["DEEPSEEK_API_KEY"]

    @property
    def base_url(self) -> str:
        return "https://api.deepseek.com"

    @property
    def model(self) -> str:
        return "deepseek-chat"


adapters: dict[str, Adapter] = {
    "copilot": Copilot(),
    "deepseek": Deepseek(),
}

parser = ArgumentParser()
parser.add_argument(
    "--adapter",
    type=str,
    default=os.environ.get("LLM_ADAPTER", "copilot"),
    choices=adapters.keys(),
)
parser.add_argument(
    "--role",
    type=str,
    default="howto",
    choices=prompts_lib.keys(),
)


def main():
    args = parser.parse_args()

    adapter = adapters[args.adapter]
    system_prompt = prompts_lib[args.role]

    input = sys.stdin.read()
    ans = adapter.ask(input, system_prompt)
    print(ans)


if __name__ == "__main__":
    main()
