#!/usr/bin/env python
import base64
import sys

import yaml


class LiteralStr(str):
    pass


def literal_str_representer(dumper, data):
    return dumper.represent_scalar("tag:yaml.org,2002:str", data, style="|")


yaml.add_representer(LiteralStr, literal_str_representer)


def decode_secret(secret_data: dict[str, str]) -> dict[str, str]:
    decoded = {}
    for key, encoded_value in secret_data.items():
        value = base64.b64decode(encoded_value).decode("utf-8")
        if "\n" in value:
            decoded[key] = LiteralStr(value)
        else:
            decoded[key] = value
    return decoded


def main():
    secret = yaml.safe_load(sys.stdin)
    assert secret
    secret_data = secret["data"]
    secret["stringData"] = decode_secret(secret_data)
    yaml.dump(secret, sys.stdout, default_flow_style=False, allow_unicode=True)


if __name__ == "__main__":
    main()
