#!/usr/bin/env python
import base64
import sys
from typing import Any

import yaml
from yaml.dumper import Dumper
from yaml.loader import Loader
from yaml.nodes import ScalarNode


class LiteralStr(str):
    pass


def literal_str_representer(dumper: Dumper, data: LiteralStr) -> ScalarNode:
    node = dumper.represent_scalar("tag:yaml.org,2002:str", data, style="|")
    return node


def literal_str_constructor(loader: Loader, node: ScalarNode) -> str | LiteralStr:
    if node.style == "|":
        return LiteralStr(node.value)
    return loader.construct_scalar(node)


class MyDumper(Dumper):
    pass


class MyLoader(Loader):
    pass


MyDumper.add_representer(LiteralStr, literal_str_representer)
MyLoader.add_constructor("tag:yaml.org,2002:str", literal_str_constructor)


def decode_secret(secret_data: dict[str, str]) -> dict[str, str | LiteralStr]:
    decoded: dict[str, str | LiteralStr] = {}
    for key, encoded_value in secret_data.items():
        value = base64.b64decode(encoded_value).decode("utf-8")
        if "\n" in value:
            decoded[key] = LiteralStr(value)
        else:
            decoded[key] = value
    return decoded


def main():
    parsed = yaml.load(sys.stdin, Loader=MyLoader)
    if parsed is None:
        return
    if parsed["kind"] == "List":
        items: list[dict[str, Any]] = parsed.get("items", [])
        for item in items:
            secret_data: dict[str, str] = item["data"]
            item["stringData"] = decode_secret(secret_data)
    else:
        secret_data: dict[str, str] = parsed["data"]
        parsed["stringData"] = decode_secret(secret_data)
    yaml.dump(
        parsed,
        sys.stdout,
        Dumper=MyDumper,
        default_flow_style=False,
        allow_unicode=True,
        sort_keys=False,
    )


if __name__ == "__main__":
    main()
