fork = true

[font]
normal = "FiraCode Nerd Font Mono"
style = "Retina"
size = 12

[font.bold]
family = "FiraCode Nerd Font Mono"
style = "Bold"

[font.italic]
family = "Fira Code"
style = "RegularItalic"

[font.bold_italic]
family = "Fira Code"
style = "BoldItalic"
