fork = true

[font]
normal = "FiraCode Nerd Font Mono"
style = "Retina"
size = 15

[font.bold]
family = "FiraCode Nerd Font Mono"
style = "Bold"

[font.italic]
family = "Fira Mono"
style = "Regular Italic"

[font.bold_italic]
family = "Fira Mono"
style = "Bold Italic"
