name: lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  luacheck:
    name: LuaCheck
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
      - name: install luacheck
        run: |
          sudo apt-get update
          sudo apt-get install -qq -y luarocks
          sudo luarocks install luacheck
      - name: check
        run: |
          luacheck --no-color config/nvim/
  stylua:
    name: Stylua
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
      - uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: v0.20.0
          args: --color always --check config/nvim/lua/
